export const ADD_PARKING = "ADD_PARKING";
export const DELETE_PARKING = "DELETE_PARKING";
export const ADD_PRIVATE_PARKING = "ADD_PRIVATE_PARKING";
export const DELETE_PRIVATE_PARKING = "ADD_PRIVATE_PARKING";